###
GET http://localhost:3000/api/app
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzIiwic3ViIjoyLCJpYXQiOjE1OTYyODYwNDYsImV4cCI6MTU5NjI4NjEwNn0.ZGVJiLd1Hwghv-rCQ2upRJTuWYVFgFdEwZlmeWKeiKs

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "chris",
    "password": "secret"
}