###
GET http://localhost:3000/api/app
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjI5Mzc3ODI2LCJleHAiOjE2MjkzNzc4ODZ9.qG81DBOVM_z02S81aTlZs-bG5zT7vUOLWMyhtH0WdNs

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "chris@gmail.com",
    "password": "secret"
}

###
POST http://localhost:3000/api/user/dummy

{

}

###
GET http://localhost:3000/api/content/fetch

###
# register user
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "name": "sandeep",
    "email": "me@sandee.com"
}
